### ISSUE TITLE
Fix flakey tests

### ISSUE THREAD

**Issue by ajaska** [ATRAN2/fureon#7]
- `test_get_random_song` in [test_song](https://github.com/ATRAN2/fureon/blob/5730c5810c760a6149b0c64091fd2e47051d0d5f/backend/tests/models/test_song.py#L114) will fail randomly with [probability approximately 8.5%](https://gist.github.com/ajaska/8f2b6edb018465282757).
- `test_initialize_stream` [test_site_controls](https://github.com/ATRAN2/fureon/blob/5730c5810c760a6149b0c64091fd2e47051d0d5f/backend/tests/test_site_controls.py#L67) will occasionally fail the `mock_run.called` check. This is the result of a race condition between the time from when self.stream_player_watcher.start() is called, and when self.stream_player_watcher.run() is actually started. If the first thread gets to the mock_run.called check first, the test will fail. From testing, this appears to happen about 10% of the time.
  - Recommendation: maybe add a short (0.2s should work) `time.sleep` before the assert

**Comment by ATRAN2** [comment]
Added a sleep to the second test as suggested. Also added a retry_test_n_times decorator for flaky tests that will try the test again a specific amount of times until it passes. At 3 attempts it should get the failure rate of the first flaky test to 0.06%.

**Comment by ajaska** [comment]
Looks like this was resolved in 1f12e5ddc37e2eb04d58f3e9e13aa94662344083.
